### ISSUE TITLE
查看dashboard中的绘图时速度较慢，如何调试和debug

### ISSUE THREAD

**Issue by wkshare** [open-falcon/graph#1]
该如何定位慢的原因？有最佳实践吗？
一次性查看30台机器的数据，counter视图。大约3-4秒，有时要多次刷新才出现。endpoint视图快一些。
如何提高查询速度。

**Comment by niean** [comment]
https://github.com/open-falcon/doc/wiki/Deploy-Practise

**Comment by laiwei** [comment]
@wkshare 看看我们的部署最佳实践

另外，你可以调整下 dashboard/gunicorn.conf中的worker数量，默认是4个worker，调大一些，会有帮助

**Comment by wkshare** [comment]
@laiwei 好，试试
