### ISSUE TITLE
graph和数据库连接超过最大等待时间

### ISSUE THREAD

**Issue by nethibernate** [open-falcon/graph#10]
现在graph和mysql连接后，是否对wait_timeout的心跳检测，今天在日志中发现了如下日志：
[MySQL] 2015/09/14 14:52:41 packets.go:118: write tcp 127.0.0.1:3306: broken pipe
[MySQL] 2015/09/14 14:52:41 packets.go:118: write tcp 127.0.0.1:3306: broken pipe
[MySQL] 2015/09/14 14:52:41 packets.go:118: write tcp 127.0.0.1:3306: broken pipe
[MySQL] 2015/09/14 14:52:41 packets.go:118: write tcp 127.0.0.1:3306: broken pipe
如果有该如何配置呢？

**Comment by nethibernate** [comment]
@laiwei @niean 谁来说明一下？看了代码，貌似没有找到数据库连接池里处理mysql wait_timeout的检测。

**Comment by laiwei** [comment]
稍等，我们来确认下

**Comment by niean** [comment]
@nethibernate 
1. broken pipe的错误，是由于mysql的server端wait_timeout后、连接不可用导致的。我们选用的mysql连接池有错误重试功能，虽然打印了错误日志，但数据最终可以正确写入到mysql
2. graph已经修复了这个问题，不会再有这个错误日志，请注意查看最新代码commit
3. 是否可以通过设置wait_timeout、来避免这个错误日志，正在尝试中，有结论了，会贴出

**Comment by niean** [comment]
可以通过设置server端的wait_timeout，来防止mysql连接broken pipe的错误。
修改方式为: 配置文件中db.dsn配置，添加一个参数"wait_timeout=604800"。一个例子，如下：
"dsn": "root:@tcp(1:3306)/graph2.0.0.172?loc=Local&parseTime=true&wait_timeout=604800"，wait_timeout设置为7天。
