### ISSUE TITLE
dashboard 空白 errno: 0x023a, str:opening error

### ISSUE THREAD

**Issue by LittlePeng** [open-falcon/graph#12]
root@fdc055cabfe3:/home/work/open-falcon# cat logs/graph.log
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error
errno: 0x023a, str:opening error

使用docker镜像默认配置部署的，dashboard 全部是空白没数据，发现这个错误信息, 不明白什么意思。

 "rrd": {
        "storage": "/home/work/open-falcon/data/6070"
    },
这个目录下是空的，感觉是写数据打开文件失败？，但root启动有写入权限的

**Comment by niean** [comment]
这个错误日志 是说磁盘忙、写入数据有少量失败，不是没有写权限，也不会导致dashboard空白。

按照book里的faq排查下吧。

聂安

**Comment by LittlePeng** [comment]
docker中的版本比较低，升级到最新0.0.5版本解决

**Comment by cloverstd** [comment]
我也遇到了同样的问题

我在 Docker 里运行，graph 是自己在 Alpine 里编译的
golang 版本为 1.7
graph 的版本是 0.5.6
graph 的 git commit 是 [2d27dc2b37ed3626e1bb51f3bf257dd97cd1979e](https://github.com/open-falcon/graph/commit/2d27dc2b37ed3626e1bb51f3bf257dd97cd1979e)
