### ISSUE TITLE
程序运行出错: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by wdystone** [open-falcon/graph#17]
程序运行一会出这个错误

errno: 0x023a, str:opening error
errno: 0panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 23 [running]:
panic(0x90e0a0, 0xc8203d24e0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/open-falcon/rrdlite.(_Updater).update(0xc820032de8, 0xc82039b3c0, 0x6, 0x8, 0x0, 0x0)
    /home/work/workspace/src/github.com/open-falcon/rrdlite/rrd_c.go:70 +0x100
github.com/open-falcon/rrdlite.(_Updater).Update(0xc820032de8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/work/workspace/src/github.com/open-falcon/rrdlite/rrd.go:130 +0x27f
github.com/open-falcon/graph/rrdtool.update(0xc8203ae9b0, 0x46, 0xc8203a9020, 0x6, 0x6, 0x0, 0x0)
    /home/work/workspace/src/github.com/open-falcon/graph/rrdtool/rrdtool.go:117 +0x45e
github.com/open-falcon/graph/rrdtool.flushrrd(0xc8203ae9b0, 0x46, 0xc8203a9020, 0x6, 0x6, 0x0, 0x0)
    /home/work/workspace/src/github.com/open-falcon/graph/rrdtool/rrdtool.go:142 +0x1a2
github.com/open-falcon/graph/rrdtool.ioWorker()
    /home/work/workspace/src/github.com/open-falcon/graph/rrdtool/sync_disk.go:95 +0x38f
created by github.com/open-falcon/graph/rrdtool.Start
    /home/work/workspace/src/github.com/open-falcon/graph/rrdtool/rrdtool.go:54 +0x24f

**Comment by laiwei** [comment]
@yubo 在跟进了，已大概确定问题

**Comment by laiwei** [comment]
https://github.com/open-falcon/rrdlite/pull/2

回头我们测试一下

**Comment by hitripod** [comment]
go 1.6 对这检查的比较严格
https://github.com/ry/v8worker/issues/31

**Comment by hsqlu** [comment]
只有go 1.6编译会出现这个问题吗？
[go1.6中cgo的变化](http://tonybai.com/2016/02/21/some-changes-in-go-1-6/)

现在解决的怎么样了？

**Comment by laiwei** [comment]
fixed  https://github.com/open-falcon/rrdlite/pull/2

**Comment by laiwei** [comment]
@hsqlu 可以测试下

**Comment by hsqlu** [comment]
@laiwei works well now.  Thanks

**Comment by andyxning** [comment]
- golang 1.6中关于添加Go和Cgo之间传递指针的限制[commit](https://github.com/golang/go/commit/9dcc58c3d139ee0475fdaca8119812c014ec5ba1)  
- 这个特性默认开启，可以通过`GODEBUG=cgocheck=0`关闭。

**Comment by laiwei** [comment]
@andyxning :+1:

**Comment by niean** [comment]
@andyxning 👍
