### ISSUE TITLE
rrd数据文件的存储路径

### ISSUE THREAD

**Issue by wkshare** [open-falcon/graph#2]
```
"rrd": {
    "storage": "/home/work/data/6070"
}
```

这段storage的配置，是否可以配置多个？
如果可以，该怎么配置？
不可以，若需要多个存储目录，该怎么配置？启动多个graph实例吗？还是咋整

**Comment by UlricQin** [comment]
一个graph管辖的rrd文件只能写到此处配置的storage中，只能配置一个地址。

如果需要多个存储目录，要启动多个graph实例。不过最佳实践是一台机器只部署一个graph，因为一个graph实例是可以充分利用磁盘io的，单机部署多个graph实例没用，而且管理麻烦。

**Comment by wkshare** [comment]
thks
