### ISSUE TITLE
push监控数据时，出现 write tcp 127.0.0.1:3306: broken pipe

### ISSUE THREAD

**Issue by QianLongGit** [open-falcon/graph#20]
最近做tomcat的监控数据push到agent时，发现DashBoard上图标全是空白的，然后看falcon的日志，发现graph的app.log总是在报错：
[mysql] 2016/05/09 14:51:04 packets.go:33: unexpected EOF
[mysql] 2016/05/09 14:51:04 packets.go:124: write tcp 127.0.0.1:3306: broken pipe
[mysql] 2016/05/09 14:51:04 packets.go:124: write tcp 127.0.0.1:3306: broken pipe
[mysql] 2016/05/09 14:51:18 packets.go:33: unexpected EOF
[mysql] 2016/05/09 14:51:18 packets.go:124: write tcp 127.0.0.1:3306: broken pipe

是不是这里写数据库失败，导致DashBoard上都是空白 啊

**Comment by itxx00** [comment]
检查下数据库连接和相关配置

**Comment by QianLongGit** [comment]
配置应该是没问题的。因为我们监控的zookeeper数据也是和tomcat一样在push到falcon agent 上。zookeeper的监控数据一切正常，DashBoard上zookeeper的监控图也是正常显示，只有tomcat的监控图全是空白。而且zookeeper和tomcat的json数据结构也是一样的。我们也在尽力排查原因。但现在还一点头绪都没有
