### ISSUE TITLE
多次上报某个metric在同一个timestamp的数据

### ISSUE THREAD

**Issue by chrislee87** [open-falcon/graph#23]
现在group模块对metric在同一个timestamp的数据只保留收到的第一份，但业务上我们需要实现类似update的功能，数据有了变化会多次发送timestamp相同的数据。简单把下面代码中的continue去掉会到导致程序错误，有什么好的建议吗？

```
    proc.GraphRpcRecvCnt.Incr()

    // To Graph
    first := store.GraphItems.First(key)
    if first != nil && items[i].Timestamp <= first.Timestamp {
        continue
    }
    store.GraphItems.PushFront(key, items[i], checksum, cfg)

    // To Index
    index.ReceiveItem(items[i], checksum)

    // To History
    store.AddItem(checksum, items[i])
```

**Comment by laiwei** [comment]
> 但业务上我们需要实现类似update的功能，数据有了变化会多次发送timestamp相同的数据

这个业务场景，你可能需要转换一下，graph不支持这样的场景

**Comment by EliseCheng** [comment]
如果一开始在该时间点没有上报数据，查询该时间戳的数据是null，后面可以 补上这个时间戳的数据吗？我试着给定这个时间戳的值再次push data，发现这个值仍然是null，是不是和 @chrislee87 的问题相同，不能支持update的问题

**Comment by laiwei** [comment]
上报数据只能追加，按照时间戳升序。 @EliseCheng
