### ISSUE TITLE
graph连接mysql的疑问

### ISSUE THREAD

**Issue by chrislee87** [open-falcon/graph#24]
MySQL只需要配一台吗？graph集群里的多个graph连接的是同一个mysql？
类似的问题，多个judge连接的也是同一个redis实例？

**Comment by 710leo** [comment]
是的，连接的是同一个msyql，为了保证高可用可以把mysql配置成主从模式

**Comment by qingmu-io** [comment]
请问如何添加mysql的密码

**Comment by luochongchongchong** [comment]
g.InitDB, get db conn fail this authentication plugin is not supported,这个错误怎么解决,已经把mysql认证方式换成mysql_native_password还是不行
