### ISSUE TITLE
为什么代码要写死MIN_STEP = 30s呢

### ISSUE THREAD

**Issue by EliseCheng** [open-falcon/graph#29]
代码http/debug_http.go中 141行
if item.Step < g.MIN_STEP {
                item.Step = g.MIN_STEP
}
为什么步长小于30s的强制设定成30s呢，而且是写死没法配置，不太理解，这个设计是出于什么考虑

**Comment by laiwei** [comment]
min_step 是可以配置的，参考transfer/cfg.json中的配置项
