### ISSUE TITLE
关于使用RRD进行存储的疑问

### ISSUE THREAD

**Issue by wkshare** [open-falcon/graph#3]
“我们参考RRDtool的理念，在数据每次存入的时候，会自动进行采样、归档。在默认的归档策略，一分钟push一次的频率下，历史数据保存5年。同时为了不丢失信息量，数据归档的时候，会按照平均值采样、最大值采样、最小值采样存三份。用户在查询某个metric，在过去一年的历史数据时，Graph会选择最合适的采样频率，返回采样过后的数据，提高了数据查询速度。”

对这段话，有几个疑问：
1、数据每次存入，怎么理解？什么情况下会触发一次数据存储？一次的存入量，怎么衡量？
2、一分钟push一次的频率下，历史数据保存5年。频率降低的话，是否可以存储更久的数据？
3、对于较久远的历史数据，保存的数据点会不会减少？

**Comment by UlricQin** [comment]
@niean  @yubo

**Comment by laiwei** [comment]
1. 每次存入，就是用户每个周期，push一次数据的时候。
2. 历史数据的保存时间，可以调整，你也可以调整为10年，那么磁盘空间的使用会稍微增多。频率越低，在浪费相同磁盘空间的情况下，当然存的时间会更久。
3. 是的，久远的数据，会被采样存储。

**Comment by wkshare** [comment]
thks, @laiwei
