### ISSUE TITLE
关于rrd存储的疑问

### ISSUE THREAD

**Issue by LeonQiuM** [open-falcon/graph#34]
在我们线上部署graph后，rrd数据存储量非常大，结合rrd存储的相关概念，由于不懂开发语言，线上已经部署，所以有以下疑问紧急请教以下：
1.按照文档的解释，我得理解是：graph将采集的数据通过rrd的方式存储，同一个metric存一个rrd文件，rrd文件大小事固定的，相同metric在不同时间点的数据采集上来都在同一个rrd文件中，直至rrd环被写满，默认情况是五年，但是我们线上的graph数据存储目录下的rrd文件数量在不断的增长，只是磁盘使用情况非常的巨大。
2.线上监控的项目中包括nginx和mysql，插件用得open-falcon官方推荐的，这些采集的metric数量比较大，会不会产生他们的metric疯狂创建rrd文件的情况
非常感谢！！！

**Comment by LeonQiuM** [comment]
这个nginx监控上有一定的漏洞，当nginx的api接口参数为动态变化的时候，graph会疯狂创建rrd文件

**Comment by laiwei** [comment]
是的，这是ngx监控插件的问题，如果你的url本身非常离散，那么就会当做不同的counter，创建很多的rrd文件。
