### ISSUE TITLE
hashKey()返回值为uint32强转成int,idx计算出来为负数，直接panic了

### ISSUE THREAD

**Issue by huzhengchuan** [open-falcon/graph#6]
store/storage.go 文件中

<pre><code>func (this *GraphItemMap) First(key string) *cmodel.GraphItem {
    this.RLock()
    defer this.RUnlock()
    idx := int(hashKey(key)) % this.Size
    L, ok := this.A[idx][key]
</code></pre>
- hashKey()函数返回值为uint32的，如果返回的值为3061298526，计算出来的idx为负数，graph直接
  panic。
  神人，帮着看一下^_^

**Comment by laiwei** [comment]
@niean

**Comment by niean** [comment]
把你panic的日志，贴一下~~

**Comment by huzhengchuan** [comment]
2015/06/01 23:10:55 cfg.go:80: read config file: cfg.json successfully
2015/06/01 23:10:55 db.go:58: makeDbConn  root:Wxt130506@tcp(127.0.0.1:3306)/graph?loc=Local&parseTime=true
2015/06/01 23:10:55 db.go:27: g.InitDB, ok
2015/06/01 23:10:55 index.go:14: index:Start, ok
2015/06/01 23:10:55 rpc.go:53: rpc listening 0.0.0.0:6070
2015/06/01 23:10:55 http.go:87: http listening 0.0.0.0:6071
2015/06/01 23:10:55 main.go:23: 3281 register signal notify
panic: runtime error: index out of range

goroutine 20 [running]:
runtime.panic(0x82c7fa0, 0x8649e57)
    /usr/lib/go/src/pkg/runtime/panic.c:266 +0x9a
github.com/open-falcon/graph/store.(_GraphItemMap).First(0x1891c360, 0x189cc8a0, 0x20, 0x0)
    /opt/devops/open-falcon/src/github.com/open-falcon/graph/store/store.go:70 +0x12f
github.com/open-falcon/graph/api.handleItems(0x189cb160, 0x56, 0x56)
    /opt/devops/open-falcon/src/github.com/open-falcon/graph/api/graph.go:59 +0x111
created by github.com/open-falcon/graph/api.(_Graph).Send
    /opt/devops/open-falcon/src/github.com/open-falcon/graph/api/graph.go:27 +0x3f

goroutine 1 [chan receive]:
main.start_signal(0xcd1, 0x1891cd50, 0x28, 0x189008e8, 0x4, ...)
    /opt/devops/open-falcon/src/github.com/open-falcon/graph/main.go:27 +0x1b5
main.main()
    /opt/devops/open-falcon/src/github.com/open-falcon/graph/main.go:82 +0x2a0

goroutine 3 [syscall]:
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1394

**Comment by niean** [comment]
遍历测试，问题没有复现。可能跟环境有关。私聊下吧。

**Comment by niean** [comment]
32位golang，uint32强转int为32、存在溢出问题。已修改代码中的问题。
