### ISSUE TITLE
请问graph数据库的表结构在哪里啊?

### ISSUE THREAD

**Issue by songkingkong** [open-falcon/graph#9]
2015/07/16 17:09:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:10:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:10:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:11:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:11:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:12:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:12:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:13:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:13:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:14:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:14:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist
2015/07/16 17:15:00 index_update_incr_task.go:90: 127.0.0.1 Error 1146: Table 'graph.endpoint' doesn't exist

**Comment by itxx00** [comment]
@364960041  看这里 https://github.com/open-falcon/scripts/tree/master/db_schema

**Comment by laiwei** [comment]
嗯，或者直接参考 http://book.open-falcon.com/zh/install/prepare.html
